version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: smartCampusService
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: smartCampusServicedb
    ports:
      - "5433:5432"
    volumes:
      - smartcampus_pgdata:/var/lib/postgresql/data


volumes:
  smartcampus_pgdata: